testing: false

# Site settings
title: "Linear Algebra (Spring 2026)"
page_title: "MATH 3120 â€” Linear Algebra"
course_title: "UPenn MATH 3120, Spring 2026."
description: "Course website"
instructor: "Danny Krashen"
email: "daniel.krashen+lalg@gmail.com"
office: "DRL 3E1A"
office_hours: "TBD"
lecture_schedule: "Mon/Wed 1:45-3:15 LRSM AUD"

baseurl: "/lalg-spring26"
url: "http://dkrashen.github.io"

# url: "localhost:4000"
# url: "http://math.dkrashen.org"

# Build settings
markdown: kramdown
permalink: pretty
